version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=newgeekstore
      - POSTGRES_USER=usergeek
      - POSTGRES_PASSWORD=usergeek123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=geeker@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=usergeek123
    ports:
      - 5050:80

